name: voucher_generator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  router_os_client: ^2.0.0
  flutter_bloc: ^9.1.0
  sqflite: ^2.4.1
  path: ^1.9.1
  equatable: ^2.0.7
  dart_ping: ^9.0.1
  network_info_plus: ^7.0.0
  http: ^1.6.0
  network_tools: ^5.0.6
  path_provider: ^2.1.5
  drift: ^2.31.0
  sqlite3_flutter_libs: ^0.6.0+eol
  internet_speed_meter: ^1.0.3
  wifi_scan: ^0.4.1+2
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
